### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by g4c3** [Exynos7880-Linux/samsung-exynos7880#3]
Hello everyone.
I've followed the buid steps and at ./build.sh -b bd I become the error from the attached file. 
[compile_error.txt](https://github.com/Exynos7880-Linux/samsung-exynos7880/files/11039398/compile_error.txt)

What I am doing wrong?
Thanks in advance!

**Comment by exeliffy** [comment]
Sorry, I don't know how to fix it or what you're doing wrong, just wanted to comment because im experiencing the same problem

**Comment by aymanrgab** [comment]
`ccache: error: execute_noreturn of /home/evgeni/aTools/samsung-exynos7880/bd/downloads/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc failed: No such file or directory`

**Comment by exeliffy** [comment]
I managed to fix that one, although mine wasn't the exact same, but still had to do with ccache, but i had a lot of other issues building the project as well. i dont have access to my build machine right now, but i could rebuild it and provide you with logs, because eventually i gave up on building it myself.

**Comment by g4c3** [comment]
@exeliffy I've tryed with fresh installation of Ubuntu Jammy, but still the same error. What kind of distro are you using?

**Comment by g4c3** [comment]
@aymanrgab I saw that from the error message, but the file is there. Can be from the ccache version or some other package?

**Comment by exeliffy** [comment]
@g4c3 I’m using Ubuntu Focal, as it is generally a bit more supported. Did you also make sure that ccache is (correctly) in your $PATH?

**Comment by aymanrgab** [comment]
@g4c3 What system are you building on ?

**Comment by g4c3** [comment]
@exeliffy yes, I've tried that also, following https://askubuntu.com/questions/470545/how-do-i-set-up-ccache
@aymanrgab I've tried with Jammy and with Focal. But ending with the same error. Installed packages: curl, make 4.2.1 , build-essential 12.8ubuntu1.1 and ccache 3.3.7.
